# Generated by Django 6.0.5 on 2026-05-20 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenido', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_decaimiento', models.FloatField(default=0.85, help_text='Factor λ del decaimiento temporal (0 < λ ≤ 1). Multiplica el peso de eventos cada día de antigüedad.')),
                ('umbral_similitud', models.FloatField(default=0.3, help_text='Puntuación mínima (0–1) para incluir un recurso en la recomendación.')),
                ('max_recomendaciones', models.PositiveSmallIntegerField(default=8, help_text='Número máximo de recursos a recomendar por sesión.')),
                ('peso_valoracion_util', models.FloatField(default=0.2, help_text='Peso adicional para recursos con valoración "útil" del estudiante.')),
                ('dias_ventana_clickstream', models.PositiveSmallIntegerField(default=30, help_text='Días hacia atrás a considerar para el procesamiento de Clickstream.')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Motor',
                'verbose_name_plural': 'Configuración del Motor',
                'db_table': 'configuracion_motor',
            },
        ),
        migrations.CreateModel(
            name='EventoClickstream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('clic', 'Clic en recurso'), ('permanencia', 'Permanencia en URL'), ('retorno', 'Retorno a recurso'), ('cierre', 'Cierre de recurso')], max_length=20)),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('procesado', models.BooleanField(db_index=True, default=False)),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='eventos_clickstream', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(db_column='recurso_id', on_delete=django.db.models.deletion.CASCADE, related_name='eventos_clickstream', to='contenido.recurso')),
            ],
            options={
                'verbose_name': 'Evento Clickstream',
                'verbose_name_plural': 'Eventos Clickstream',
                'db_table': 'evento_clickstream',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPerfilVARK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_anterior', models.JSONField()),
                ('vector_nuevo', models.JSONField()),
                ('origen', models.CharField(choices=[('clickstream', 'Procesamiento Clickstream'), ('quiz', 'Resultado de Quiz'), ('test_inicial', 'Test VARK Inicial')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial_perfil_vark', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial Perfil VARK',
                'verbose_name_plural': 'Historial Perfil VARK',
                'db_table': 'historial_perfil_vark',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.FloatField()),
                ('justificacion', models.TextField()),
                ('vector_vark_snapshot', models.JSONField()),
                ('fecha_recomendacion', models.DateTimeField(auto_now_add=True)),
                ('vista', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(db_column='recurso_id', on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='contenido.recurso')),
                ('tema', models.ForeignKey(db_column='tema_id', on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='contenido.tema')),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
                'db_table': 'recomendacion',
                'ordering': ['-fecha_recomendacion', '-puntuacion'],
            },
        ),
        migrations.CreateModel(
            name='ValoracionRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.CharField(choices=[('util', 'Útil'), ('no_util', 'No útil')], max_length=10)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(db_column='recurso_id', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='contenido.recurso')),
            ],
            options={
                'verbose_name': 'Valoración de Recurso',
                'verbose_name_plural': 'Valoraciones de Recursos',
                'db_table': 'valoracion_recurso',
                'unique_together': {('estudiante', 'recurso')},
            },
        ),
    ]
