# Generated by Django 6.0.5 on 2026-06-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='grupo_experimento',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
