# Generated by Django 6.0.5 on 2026-06-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacion', '0002_recomendacion_grupo_experimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmotor',
            name='peso_cbf',
            field=models.FloatField(default=0.6, help_text='Peso de la similitud coseno (CBF) en el score final (0–1).'),
        ),
        migrations.AddField(
            model_name='configuracionmotor',
            name='peso_ml',
            field=models.FloatField(default=0.4, help_text='Peso de la probabilidad de utilidad del modelo ML en el score final (0–1).'),
        ),
        migrations.AddField(
            model_name='configuracionmotor',
            name='usar_ml',
            field=models.BooleanField(default=True, help_text='Si está activo y hay modelo entrenado, combina ML con CBF. Si no, solo CBF.'),
        ),
    ]
