# Generated by Django 6.0.5 on 2026-05-20 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenido', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentoAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado')], default='activo', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(db_column='creado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experimentos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experimento A/B',
                'verbose_name_plural': 'Experimentos A/B',
                'db_table': 'experimento_ab',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nuevo_recurso', 'Nuevo recurso disponible'), ('nuevo_quiz', 'Nuevo quiz disponible'), ('sistema', 'Mensaje del sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(db_column='destinatario_id', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(blank=True, db_column='recurso_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='contenido.recurso')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionExperimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('experimental', 'Experimental (recomendación VARK)'), ('control', 'Control (sin personalización)')], max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_experimento', to=settings.AUTH_USER_MODEL)),
                ('experimento', models.ForeignKey(db_column='experimento_id', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='analitica.experimentoab')),
            ],
            options={
                'verbose_name': 'Asignación Experimento',
                'verbose_name_plural': 'Asignaciones Experimento',
                'db_table': 'asignacion_experimento',
                'unique_together': {('experimento', 'estudiante')},
            },
        ),
    ]
