# Generated by Django 6.0.5 on 2026-05-07 06:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('administrador', 'Administrador')], default='estudiante', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='PerfilVARK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_visual', models.FloatField(default=0.0)),
                ('puntaje_auditivo', models.FloatField(default=0.0)),
                ('puntaje_lectura', models.FloatField(default=0.0)),
                ('puntaje_kinestesico', models.FloatField(default=0.0)),
                ('test_completado', models.BooleanField(default=False)),
                ('fecha_test', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_vark', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil VARK',
                'verbose_name_plural': 'Perfiles VARK',
                'db_table': 'perfil_vark',
            },
        ),
        migrations.CreateModel(
            name='SesionTestVARK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preguntas_json', models.JSONField()),
                ('completado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_test_vark', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión Test VARK',
                'verbose_name_plural': 'Sesiones Test VARK',
                'db_table': 'sesion_test_vark',
            },
        ),
    ]
