# Generated by Django 6.0.5 on 2026-06-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='carrera',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usuario',
            name='semestre',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
