# Generated by Django 6.0.5 on 2026-06-22 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_carrera_usuario_foto_usuario_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTestVARK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('dinamico_ia', 'Generación dinámica con IA'), ('banco_fijo', 'Banco fijo de preguntas')], default='dinamico_ia', max_length=20)),
                ('num_preguntas', models.PositiveSmallIntegerField(default=15)),
                ('contexto_tematico', models.CharField(default='aprender conceptos de programación (algoritmos, estructuras de datos, POO)', max_length=200)),
                ('usar_fallback', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Test VARK',
                'verbose_name_plural': 'Configuración Test VARK',
                'db_table': 'configuracion_test_vark',
            },
        ),
        migrations.CreateModel(
            name='PreguntaVARK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('contexto', models.CharField(blank=True, default='', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('origen', models.CharField(choices=[('ia', 'Generada por IA'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_vark_aprobadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pregunta VARK',
                'verbose_name_plural': 'Preguntas VARK',
                'db_table': 'pregunta_vark',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='OpcionVARK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('estilo', models.CharField(choices=[('V', 'Visual'), ('A', 'Auditivo'), ('R', 'Lectura/Escritura'), ('K', 'Kinestésico')], max_length=1)),
                ('peso', models.FloatField(default=1.0)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='accounts.preguntavark')),
            ],
            options={
                'verbose_name': 'Opción VARK',
                'verbose_name_plural': 'Opciones VARK',
                'db_table': 'opcion_vark',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
