# Generated by Django 6.0.5 on 2026-05-20 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subtema',
                'verbose_name_plural': 'Subtemas',
                'db_table': 'subtema',
                'ordering': ['tema', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'db_table': 'tema',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('nivel_dificultad', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Media'), ('dificil', 'Difícil')], default='facil', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(db_column='creado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_creadas', to=settings.AUTH_USER_MODEL)),
                ('subtema', models.ForeignKey(blank=True, db_column='subtema_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='contenido.subtema')),
                ('tema', models.ForeignKey(db_column='tema_id', on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='contenido.tema')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'pregunta',
            },
        ),
        migrations.CreateModel(
            name='OpcionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(db_column='pregunta_id', on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='contenido.pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Pregunta',
                'verbose_name_plural': 'Opciones de Pregunta',
                'db_table': 'opcion_pregunta',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria_vark', models.CharField(choices=[('V', 'Visual'), ('A', 'Auditivo'), ('R', 'Lectura/Escritura'), ('K', 'Kinestésico')], db_index=True, max_length=1)),
                ('nivel_complejidad', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], db_index=True, max_length=20)),
                ('tipo_formato', models.CharField(choices=[('video', 'Video'), ('articulo', 'Artículo'), ('ejercicio', 'Ejercicio'), ('documento', 'Documento')], default='articulo', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('url_valida', models.BooleanField(default=True)),
                ('ultima_verificacion', models.DateTimeField(blank=True, null=True)),
                ('sugerido_por_ia', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(db_column='creado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_creados', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, db_column='validado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_validados', to=settings.AUTH_USER_MODEL)),
                ('subtema', models.ForeignKey(blank=True, db_column='subtema_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='contenido.subtema')),
                ('tema', models.ForeignKey(db_column='tema_id', on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='contenido.tema')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'db_table': 'recurso',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SugerenciaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('descripcion', models.TextField(blank=True)),
                ('justificacion_pedagogica', models.TextField()),
                ('categoria_vark', models.CharField(choices=[('V', 'Visual'), ('A', 'Auditivo'), ('R', 'Lectura/Escritura'), ('K', 'Kinestésico')], max_length=1)),
                ('nivel_complejidad', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=20)),
                ('tipo_formato', models.CharField(choices=[('video', 'Video'), ('articulo', 'Artículo'), ('ejercicio', 'Ejercicio'), ('documento', 'Documento')], default='articulo', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_sugerencia', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('recurso_creado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencia_origen', to='contenido.recurso')),
                ('revisado_por', models.ForeignKey(blank=True, db_column='revisado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_revisadas', to=settings.AUTH_USER_MODEL)),
                ('tema', models.ForeignKey(db_column='tema_id', on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias_ia', to='contenido.tema')),
            ],
            options={
                'verbose_name': 'Sugerencia IA',
                'verbose_name_plural': 'Sugerencias IA',
                'db_table': 'sugerencia_ia',
                'ordering': ['-fecha_sugerencia'],
            },
        ),
        migrations.AddField(
            model_name='subtema',
            name='tema',
            field=models.ForeignKey(db_column='tema_id', on_delete=django.db.models.deletion.CASCADE, related_name='subtemas', to='contenido.tema'),
        ),
        migrations.CreateModel(
            name='ResultadoQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.FloatField()),
                ('total_preguntas', models.PositiveSmallIntegerField()),
                ('respuestas_correctas', models.PositiveSmallIntegerField()),
                ('respuestas_json', models.JSONField(help_text='[{pregunta_id, opcion_elegida_id, es_correcta}]')),
                ('fecha_realizacion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='resultados_quiz', to=settings.AUTH_USER_MODEL)),
                ('tema', models.ForeignKey(db_column='tema_id', on_delete=django.db.models.deletion.CASCADE, related_name='resultados_quiz', to='contenido.tema')),
            ],
            options={
                'verbose_name': 'Resultado Quiz',
                'verbose_name_plural': 'Resultados Quiz',
                'db_table': 'resultado_quiz',
                'ordering': ['-fecha_realizacion'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='subtema',
            unique_together={('tema', 'nombre')},
        ),
    ]
