# Generated by Django 6.0.5 on 2026-06-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='explicacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('ia', 'Generada por IA')], default='manual', max_length=10),
        ),
    ]
